version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0. --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: pdf_frontend
    ports:
      - "3000:80"  # Access UI at http://localhost:3000
    depends_on:
      - backend